name: Deploy Frontendwhy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: Build the Docker image
    #- run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build . --file Dockerfile --tag ksleongtech/react-test
    - run: docker run -e CI=true ksleongtech/react-test npm test
